server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}