services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      EUREKA: http://service-registry:8761/eureka/

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA: http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      CONFIG: http://config-server:8888
      EUREKA: http://service-registry:8761/eureka/
      MYSQL_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
    depends_on:
      - config-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      CONFIG: http://config-server:8888
      EUREKA: http://service-registry:8761/eureka/
      MYSQL_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    depends_on:
      - config-server
#
#  ai-service:
#    build: ./aiservice
#    container_name: ai-service
#    ports:
#      - "8087:8087"
#    environment:
#      CONFIG: http://config-server:8888
#      EUREKA: http://service-registry:8761/eureka/
#      OPENAI_API_KEY: ${OPENAI_API_KEY}
#    depends_on:
#      - config-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG: http://config-server:8888
      EUREKA: http://service-registry:8761/eureka/
      REDIS_HOST: host.docker.internal
    depends_on:
      - auth-service
      - user-service
#      - ai-service