services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      GIT: ${GIT}
      EUREKA: ${EUREKA}
    depends_on:
      - service-registry

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      ACCESS_SECRET: ${ACCESS_SECRET}
      ACCESS_TOKEN_EXPIRATION_MS: ${ACCESS_TOKEN_EXPIRATION_MS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REFRESH_PREFIX: ${REFRESH_PREFIX}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_TOKEN_EXPIRATION_MS: ${REFRESH_TOKEN_EXPIRATION_MS}
      COOKIE_PATH: ${COOKIE_PATH};
      MAX_TOKEN: ${MAX_TOKEN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      BLACKLIST_PREFIX: ${BLACKLIST_PREFIX}
      BLOCKED_PREFIX: ${BLOCKED_PREFIX}
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
    depends_on:
      - config-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - config-server
#
#  ai-service:
#    build: ./aiservice
#    container_name: ai-service
#    ports:
#      - "8087:8087"
#    environment:
#      CONFIG: http://config-server:8888
#      EUREKA: http://service-registry:8761/eureka/
#      OPENAI_API_KEY: ${OPENAI_API_KEY}
#    depends_on:
#      - config-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - auth-service
      - user-service
#      - ai-service