services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      GIT: ${GIT}
      EUREKA: ${EUREKA}
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      ACCESS_SECRET: ${ACCESS_SECRET}
      ACCESS_TOKEN_EXPIRATION_MS: ${ACCESS_TOKEN_EXPIRATION_MS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REFRESH_PREFIX: ${REFRESH_PREFIX}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_TOKEN_EXPIRATION_MS: ${REFRESH_TOKEN_EXPIRATION_MS}
      COOKIE_PATH: ${COOKIE_PATH}
      MAX_TOKEN: ${MAX_TOKEN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      BLACKLIST_PREFIX: ${BLACKLIST_PREFIX}
      BLOCKED_PREFIX: ${BLOCKED_PREFIX}
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
    depends_on:
      config-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
      DB: ${DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      config-server:
        condition: service_healthy
    volumes:
      - ./secrets:/app/secrets

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG: ${CONFIG}
      EUREKA: ${EUREKA}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      config-server:
        condition: service_healthy
      auth-service:
        condition: service_started
      user-service:
        condition: service_started