server:
  port: 2080

spring:
  application:
    name: api-gateway-test

  config:
    import: ""

  cloud:
    config:
      enabled: false
      fail-fast: false

    discovery:
      enabled: false

    gateway:
      discovery:
        locator:
          enabled: false

      routes: []

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

request-id:
  prefix: "test-request-id:"
  ttl: 1s   # sek
  value: "test-gateway"

header-request-id:
  name: "X-Test-Request-Id"

