--liquibase formatted sql

--changeset Rslan:001-create-invoice-tables

CREATE SEQUENCE invoice_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE invoice
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_number      VARCHAR(50),
    patient_id          BIGINT         NOT NULL,
    medical_facility_id BIGINT         NOT NULL,
    currency            VARCHAR(3)     NOT NULL,

    net_amount          NUMERIC(19, 2) NOT NULL,
    discount_amount     NUMERIC(19, 2) NOT NULL,
    tax_amount          NUMERIC(19, 2) NOT NULL,
    total_amount        NUMERIC(19, 2) NOT NULL,

    status              VARCHAR(20)    NOT NULL,

    issued_date         DATE,
    due_date            DATE,

    CONSTRAINT pk_invoice
        PRIMARY KEY (id),

    CONSTRAINT uk_invoice_invoice_number
        UNIQUE (invoice_number)
);


CREATE TABLE invoice_item
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_id          BIGINT         NOT NULL,
    service_id          BIGINT         NOT NULL,

    description         VARCHAR(500)   NOT NULL,

    quantity            NUMERIC(19, 4) NOT NULL,
    unit_price          NUMERIC(19, 2) NOT NULL,

    discount_rate       NUMERIC(8, 6)  NOT NULL,
    tax_rate            NUMERIC(8, 6)  NOT NULL,

    net_amount          NUMERIC(19, 2) NOT NULL,
    discount_amount     NUMERIC(19, 2) NOT NULL,
    tax_amount          NUMERIC(19, 2) NOT NULL,
    total_amount        NUMERIC(19, 2) NOT NULL,

    CONSTRAINT pk_invoice_item
        PRIMARY KEY (id),

    CONSTRAINT fk_invoice_item_invoice
        FOREIGN KEY (invoice_id)
            REFERENCES invoice (id)
);


CREATE INDEX idx_invoice_item_invoice_id
    ON invoice_item (invoice_id);