--liquibase formatted sql

--changeset Rslan:002-create-payment-tables


CREATE TABLE payment
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_id          BIGINT         NOT NULL,
    amount              NUMERIC(19, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    method              VARCHAR(50)    NOT NULL,
    status              VARCHAR(50)    NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE   NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,
    completed_at        TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_payment
        PRIMARY KEY (id),

    CONSTRAINT ck_payment_amount_positive
        CHECK ( amount > 0 )
);

CREATE INDEX idx_payment_invoice_id
    ON payment (invoice_id);