spring:
  application:
    name: ai-service-test

  config:
    import: ""

  cloud:
    config:
      enabled: false
      fail-fast: false

    discovery:
      enabled: false

    service-registry:
      auto-registration:
        enabled: false

  cache:
    type: redis

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3:latest

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

cache:
  default-ttl: 5m

  active-prompt:
    ttl: 10m

  user-auth-info:
    ttl: 10s

ai:
  provider: ollama
  model: llama3:latest

  prompt:
    activation-retry:
      max-attempts: 3
      initial-delay: 1ms
      multiplier: 1.1
      max-delay: 2ms

request-id:
  prefix: "test:request-id:"
  value: "test"
  ttl: 5m

user-context:
  user-context-header: X-User-Context

header-request-id:
  name: X-Request-Id

request-id-filter:
  enabled: false

auth-filter:
  enabled: false

user-context-filter:
  enabled: false